# using docker container
sudo: false

language: java

jdk:
#  - openjdk6
  - oraclejdk7
  - oraclejdk8

before_script:
    - export QINIU_TEST_ENV="travis"
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
